spring.application.name=RetrievalAugmentedGeneration
#database
spring.datasource.url=jdbc:postgresql://localhost:5433/rag_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3:instruct
spring.ai.ollama.embedding.model=nomic-embed-text

#OpenAi
#spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.model=gpt-4o-mini
#spring.ai.openai.embedding.model=text-embedding-3-small


#gemini
#spring.ai.google.api-key=${GEMINI_API_KEY}
#spring.ai.google.chat.options.model=gemini-pro

# pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768