version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector-db
    restart: always
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"